spring:
  application:
    name: reactive
  liquibase:
    enabled: true
    change-log: db/changelog/main-changelog.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/reactive
    username: postgres
    password: gbhfns
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  main:
    web-application-type: reactive