spring:
  application:
    name: reactive
  liquibase:
    enabled: true
    change-log: db/changelog/main-changelog.xml
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/reactive}
    username: ${JDBC_USERNAME:postgres}
    password: ${JDBC_PASSWORD:gbhfns}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  main:
    web-application-type: reactive

jwt:
  password:
    encoder:
      secret: ${ENCODER_SECRET:FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g}
      iteration: ${ENCODER_ITERATION:64}
      keylength: ${ENCODER_KEY_LENGTH:256}
  secret: ${JWT_SECRET:8506876256f3e572b83d7d5a0b86b503c7b7e68c430d69d5307e865d8619d05f}
  expiration: ${JWT_EXPIRATION:3600}
  issuer: ${JWT_ISSUER:bank}